language: java
dist: trusty
sudo: false
jdk:
  - openjdk8
before_script:
  - chmod +x ./gradlew
script:
  - ./gradlew elki:dependencies
  - ./gradlew check --stacktrace
  - ./gradlew check -Pjacoco --stacktrace
  - ./gradlew :codeCoverageReport -Pjacoco --stacktrace
install:
  - ./gradlew assemble -Pjacoco
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
